<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="TEST_PROG" Id="{8ff9d161-157e-42ac-b3da-373105b7f816}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TEST_PROG
VAR
	FakeAxisContractTests : FB_FakeAxis_BaseUnitTests;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>