<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_PackMLModule" Id="{e5d0f60c-8d1a-48c8-9daa-cfbe39692472}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PackMLModule EXTENDS FB_PackMLModeSet
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>