<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_TestableGCModule" Id="{9c2f828e-112b-4c5e-8dde-b427c89f8b11}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TestableGCModule EXTENDS FB_GC_Module
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
    <Method Name="M_SetTestServiceStatus" Id="{9c2f828e-112b-4c5e-8dde-b427c89f8b12}">
      <Declaration><![CDATA[METHOD M_SetTestServiceStatus
VAR_INPUT
	TestStatus : ST_GC_ServiceStatus;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_ServiceStatusView.ByName := TestStatus;]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_UpdateTestAlarmList" Id="{9c2f828e-112b-4c5e-8dde-b427c89f8b13}">
      <Declaration><![CDATA[METHOD M_UpdateTestAlarmList
]]></Declaration>
      <Implementation>
        <ST><![CDATA[H_UpdateAlarmList();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>
