<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_TestableServiceBase" Id="{7adf419a-ced5-4d73-8e72-9b5f880b380e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TestableServiceBase EXTENDS FB_ServiceBase
]]></Declaration>
    <Implementation>
      <ST><![CDATA[M_UpdateService();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>
